config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  root "tasks#index"
  get "tasks", to: "tasks#index"
  get "tasks/new", to: "tasks#new", as: :new_task
  post "tasks", to: "tasks#create"
  get "tasks/:id", to: "tasks#show", as: :task
  get "tasks/:id/edit", to: "tasks#edit", as: :edit_task
  patch "tasks/:id", to: "tasks#update"
  delete "tasks/:id", to: "tasks#destroy", as: :delete_task
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/task.rb
class Task < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :set_task, only: [:show, :edit, :update, :destroy]
  def index
    @tasks = Task.all
  end

  def show
  end

  def new
    @task = Task.new
  end

  def create
    @task = Task.new(task_params)
    @task.save
    redirect_to task_path(@task)
  end

  def edit
  end

  def update
    @task.update(task_params)
    redirect_to task_path(@task)
  end

  def destroy
    @task.destroy
    redirect_to tasks_path
  end

  private

  def task_params
    params.require(:task).permit(:title, :details, :completed)
  end

  def set_task
    @task = Task.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsTaskManager1134</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v6.1.2/css/all.css">

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/tasks/_form.html.erb
<%= form_with model: task do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title %>
  <%= f.label :details %>
  <%= f.text_field :details %>
  <%= f.label :completed, for: :completed %>
  <%= f.check_box :completed %>
  <%= f.submit %>
<% end %>

app/views/tasks/edit.html.erb
<h1>Edit Task</h1>
<%= render "form", task: @task %>
<%= link_to "Back", tasks_path %>

app/views/tasks/index.html.erb
<h1>All Tasks</h1>
<% @tasks.each do |task| %>
  <p>
    <% if task.completed %>
      <%= "☑" %>
    <% else %>
      <%= "☐" %>
    <% end %>
    <%= link_to task.title, task_path(task) %>
    <%= link_to '<i class="fa-solid fa-trash-can"></i>'.html_safe, delete_task_path(task), data: {turbo_method: :delete, turbo_confirm: "Are you sure?"}
%>
  </p>
<% end %>
<%= link_to "New Task", new_task_path %>

app/views/tasks/new.html.erb
<h1>New Task</h1>
<%= render "form", task: @task %>
<%= link_to "Back", tasks_path %>

app/views/tasks/show.html.erb
<div class="container d-flex">
  <h1><%= @task.title %></h1>
  <div class="row">
    <%= @task.completed %>
  </div>
  <div class="row background-color-grey h-100">
    <%= @task.details %>
  </div>


  <%= link_to "Back", tasks_path, class: "text-decoration-none btn btn-primary" %>
  <%= link_to "Edit", edit_task_path(@task), class: "text-decoration-none" %>
  <%= link_to '<i class="fa-solid fa-trash-can"></i>'.html_safe, delete_task_path(@task), class: "text-decoration-none", data: {turbo_method: :delete, turbo_confirm: "Are you sure?"} %>
</div>